# Generated by Django 5.1.3 on 2024-11-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('publication_number', models.CharField(max_length=100)),
            ],
        ),
    ]
