# Generated by Django 5.1.3 on 2024-11-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patentapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Patent',
        ),
    ]
